---
- template: src=aliases.conf dest=/etc/httpd/conf.d/{{ _website_domain }}.conf.d/aliases.conf
  notify: verify config and restart httpd
  name: Set aliases.conf template for {{ _website_domain }}
  when: server_aliases is defined

- file: path=/etc/httpd/conf.d/{{ _website_domain }}.conf.d/aliases.conf state=absent
  when: server_aliases is undefined

