---
- name: Install httpd and related packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ httpd_package }}"
  - "{{ logrotate_package }}"

- name: Make sure httpd is running
  service:
    name: "{{ httpd_service }}"
    state: started
    enabled: yes

- name: Enable common httpd modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - status
    - filter
    - rewrite
    - headers
  when: ansible_os_family == "Debian"

- name: Install httpd configuration
  copy:
    src: "{{ item }}"
    dest: "{{ httpd_global_confdir }}/{{ item }}"
    owner: root
    group: "{{ httpd_usergroup }}"
    mode: 0644
  with_items:
  - name_vhost.conf
  - mod_status.conf
  - various.conf
  notify: restart httpd

- name: Install httpd configuration (EL6)
  copy:
    src: mod_filter.conf
    dest: "{{ httpd_global_confdir }}/"
    owner: root
    group: "{{ httpd_usergroup }}"
    mode: 0644
  when: ansible_distribution_major_version == '6' and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')
  notify: restart httpd

- name: Open firewall (EL6)
  shell: lokkit -s {{ item }}
  with_items:
  - http
  - https
  when: ansible_distribution_major_version == '6' and (ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat')

- name: Open firewall (firewalld)
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
    immediate: yes
  with_items:
  - http
  - https
  when: ansible_distribution == 'Fedora' or ansible_distribution_major_version == '7'

- name: Set _httpd_common
  set_fact:
    _httpd_common: True

