---
- name: Install mod_ssl
  package:
    name: "{{ httpd_tls }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Enable ssl httpd module
  apache2_module:
    name: ssl
    state: present
  when: ansible_os_family == "Debian"

- name: Disable ssl v3
  copy:
    src: "{{ item }}"
    dest: "{{ httpd_global_confdir }}/{{ item }}"
    owner: root
    group: "{{ httpd_usergroup }}"
    mode: 0644
  with_items:
  - remove_sslv3.conf
  notify: verify config and restart httpd

- name: Set _httpd_common_tls
  set_fact:
    _httpd_common_tls: True

