---
- name: Install WSGI support
  package:
    name: "{{ httpd_wsgi_package }}"
    state: present

- name: Enable wsgi httpd module
  apache2_module:
    name: wsgi
    state: present
  when: ansible_os_family == "Debian"

- name: Set wsgi_global.conf server-wide configuration
  template:
    src: wsgi_global.conf
    dest: "{{ httpd_global_confdir }}/wsgi_global.conf"
  notify: verify config and restart httpd

# TODO remove after May 2018
- name: "remove obsolete 'python_global.conf' conffile"
  file:
    name: "{{ httpd_global_confdir }}/python_global.conf"
    state: absent
  notify: verify config and restart httpd

- name: Set _httpd_common_wsgi
  set_fact:
    _httpd_common_wsgi: True

