---
- name: Install mod_ssl
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - mod_ssl

- name: Disable ssl v3
  copy:
    src: "{{ item }}"
    dest: "/etc/httpd/conf.d/{{ item }}"
    owner: root
    group: apache
    mode: 0644
  with_items:
  - remove_sslv3.conf
  notify: verify config and restart httpd

- name: Set _http_common_tls
  set_fact:
    _httpd_common_tls: True

