---
- name: Install WSGI support
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - mod_wsgi

- name: Set python_global.conf server-wide configuration
  template:
    src: python_global.conf
    dest: /etc/httpd/conf.d/python_global.conf
  notify: verify config and restart httpd

- name: Set _http_common_wsgi
  set_fact:
    _httpd_common_wsgi: True

