---
- name: Install WSGI support
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - mod_wsgi

- name: Set wsgi_global.conf server-wide configuration
  template:
    src: wsgi_global.conf
    dest: /etc/httpd/conf.d/wsgi_global.conf
  notify: verify config and restart httpd

# TODO remove after May 2018
- file:
    name: /etc/httpd/conf.d/python_global.conf
    state: absent
  notify: verify config and restart httpd

- name: Set http_common_wsgi
  set_fact:
    _httpd_common_wsgi: True

