- set_fact:
    key_file: "/etc/pki/tls/private/{{ _website_domain }}.key"
    cert_file: "/etc/pki/tls/certs/{{ _website_domain }}.crt"

- fail: msg="Requesting cert for {{ _website_domain }}, a certificate can only be requested for the current server ({{ ansible_fqdn }}) with the freeipa method"
  when: _website_domain != ansible_fqdn

- name: Request a freeipa certificate for httpd
  command: ipa-getcert request -f {{ cert_file }} -k {{ key_file }} -D {{ ansible_fqdn }} -K host/{{ ansible_fqdn }}
  args:
    creates: "{{ key_file }}"

- name: Link freeipa CA to httpd directory
  file:
    state: link
    src: /etc/ipa/ca.crt
    dest: "/etc/pki/tls/certs/{{ _website_domain }}.ca.crt"
