---
- name: "Verify redirect value and fail"
  fail: msg="Redirect should be a complete URL, not {{ redirect }}"
  when: "redirect is defined and not redirect | match('^https?://.*/')"

- set_fact: website_url={{ ansible_fqdn }}
  when: website_url is not defined

- include: common.yml
  when: httpd_common is not defined

- set_fact: httpd_common=True

- set_fact: use_ssl=True
  when: use_letsencrypt or use_freeipa

- file: state=directory path={{ document_root }} setype=httpd_sys_content_t owner=root mode=755 group=root
  when: document_root is defined

- file:  path=/etc/httpd/conf.d/{{ website_url }}.conf.d/ state=directory

# needed for newer apache, who requires at least 1 file for include
- copy: dest=/etc/httpd/conf.d/{{ website_url }}.conf.d/placeholder.conf content="# Placeholder"

- include: password.yml
  when: website_user is defined

- include: document_root.yml
  when: document_root is defined

- set_fact: port=80
- template: src=vhost.conf dest=/etc/httpd/conf.d/{{ website_url }}.conf owner=root group=apache mode=0644
  notify: verify config and restart httpd

- include: redirect.yml
  when: redirect is defined

- include: letsencrypt.yml
  when: use_letsencrypt

- include: freeipa.yml
  when: use_freeipa

- include: redirect_to_https.yml
  when: ssl_redirect

- set_fact: port=443
- template: src=vhost.conf dest=/etc/httpd/conf.d/{{ website_url }}_ssl.conf owner=root group=apache mode=0644
  notify: verify config and restart httpd
  when: use_ssl

