---

- name: Include common vhost variables
  include_tasks: vhost_vars.yml

- name: Include common setup of httpd
  include_tasks: common.yml
  when: httpd_common is not defined

- name: test if canonical vhost is installed
  stat:
    path: "{{ _vhost_conffile_prefix }}.conf"
  register: canonical_vhost

- name: Setup canonical vhost if not yet defined
  include_tasks: vhost.yml
  vars:
    _website_domain: "{{ ansible_fqdn }}"
    use_tls: False
    use_letsencrypt: False
    use_freeipa: False
  when: "not canonical_vhost.stat.exists"

