---
- name: "Verify redirect value and fail"
  fail: msg="Redirect should be a complete URL, not {{ redirect }}"
  when: "redirect is defined and not redirect | match('^https?://.*/')"

- include: compat.yml

- set_fact:
    _force_tls: False
    _use_tls: False
    _vhost_conffile_prefix: "/etc/httpd/conf.d/{{ _website_domain }}"
    _vhost_confdir: "/etc/httpd/conf.d/{{ _website_domain }}.conf.d"

- set_fact:
    _force_tls: "{{ force_tls }}"
  when: force_tls
  name: Set force_tls if force_tls is defined

- include: common.yml
  when: httpd_common is not defined
  name: Include common setup of httpd

- set_fact:
    httpd_common: True
  name: Set http_common

- set_fact:
    _use_tls: True
  when: use_letsencrypt or use_freeipa or use_tls
  name: Set use_tls

- include: common_tls.yml
  when: _use_tls

- include: common_python.yml
  when: wsgi_script is defined and wsgi_script

- file:
    state: directory
    path: "{{ document_root }}"
    setype: httpd_sys_content_t
    owner: root
    group: "{{ document_root_group | default('root') }}"
    mode: 0775
  when: document_root is defined
  name: Set document root configuration

- file:
    path: "{{ _vhost_confdir }}"
    state: directory
  name: Create configuration directory for {{ _website_domain }}

# needed for newer apache, who requires at least 1 file for include
- copy:
    dest: "{{ _vhost_confdir }}/placeholder.conf"
    content: "# Placeholder"
  name: Create placeholder configuration for {{ _website_domain }}

- include: password.yml
  when: website_user is defined

- include: document_root.yml

- include: server_alias.yml

- include: mod_speling.yml

- set_fact:
    port: 80

- template:
    src: vhost.conf
    dest: "{{ _vhost_conffile_prefix }}.conf"
    owner: root
    group: apache
    mode: 0644
  notify: verify config and restart httpd

- include: redirect.yml

- include: redirects.yml

- include: aliases.yml

- include: letsencrypt.yml
  when: use_letsencrypt

- include: freeipa.yml
  when: use_freeipa

- include: reverse_proxy.yml

- include: mod_security.yml
  when: use_mod_sec

- include: redirect_to_https.yml

- include: python.yml
  when: wsgi_script is defined and wsgi_script

- include: hidden_service.yml
  when: use_hidden_service

- set_fact:
    port: 443

- template:
    src: vhost.conf
    dest: "{{ _vhost_conffile_prefix }}_ssl.conf"
    owner: root
    group: apache
    mode: 0644
  notify: verify config and restart httpd
  when: _use_tls

# cleanup of variables, since they leak to subsequent role run
#
# due to https://github.com/ansible/ansible/issues/14472
- set_fact:
    _force_tls: False
    _use_tls: False
  name: Clean force_tls and use_tls
