---

- name: Include distribution variables
  include: distro_vars.yml

- name: Include common setup of httpd
  include: common.yml
  when: httpd_common is not defined

- name: Include common vhost variables
  include: vhost_vars.yml

- name: test if canonical vhost is installed
  stat:
    path: "{{ _vhost_conffile_prefix }}.conf"
  register: canonical_vhost

- name: Setup canonical vhost if not yet defined
  include: vhost.yml
  vars:
    _website_domain: "{{ ansible_fqdn }}"
    use_tls: False
    use_letsencrypt: False
    use_freeipa: False
  static: no
  when: "not canonical_vhost.stat.exists"

