---
- package:
    name: "{{ item }}"
    state: present
  with_items:
  - mod_security
  - mod_security_crs
  notify: verify config and restart httpd
  name: Install mod_security packages

- name: Disable mod_security for all vhost
  lineinfile:
    dest: /etc/httpd/conf.d/mod_security.conf
    regexp: '^(\s*)SecRuleEngine '
    line: "\\1SecRuleEngine Off"
    backrefs: yes
  notify: verify config and restart httpd

- name: Enable mod_security on a vhost
  template:
    src: mod_security.conf
    dest: "{{ _vhost_confdir }}/mod_security.conf"
  notify: verify config and restart httpd
