- name: Install package needed by htpasswd module
  package:
    name: "{{ python_passlib_package }}"
    state: present

- include_tasks: password_present.yml
  when: website_user is defined

- include_tasks: password_absent.yml
  when: website_user is not defined
