- name: Create the htpasswd file
  htpasswd:
    path: "{{ httpd_confdir }}/{{ _website_domain }}.htpasswd"
    name: "{{ website_user }}"
    password: "{{ website_password }}"
    owner: root
    group: "{{ httpd_usergroup }}"
    mode: 0640

- name: Deploy the website password protection
  template:
    src: password.conf
    dest: "{{ _vhost_confdir }}/password.conf"
  notify: verify config and restart httpd
  no_log: True
