- yum: name={{ item }} state=installed
  with_items:
  - python-passlib

- htpasswd: path=/etc/httpd/{{ website_url }}.htpasswd name={{ website_user }} password={{ website_password }} owner=root group=apache mode=0640

- template: src=password.conf dest=/etc/httpd/conf.d/{{ website_url }}.conf.d/password.conf
  notify: verify config and restart httpd
