- name: Install package needed by htpasswd module
  package: name={{ item }} state=present
  with_items:
  - python-passlib

- include: password_present.yml
  when: website_user is defined

- include: password_absent.yml
  when: website_user is not defined


