- name: Install package needed by htpasswd module
  package: name={{ item }} state=present
  with_items:
  - python-passlib

- name: Create the htpasswd file 
  htpasswd: path=/etc/httpd/{{ _website_domain }}.htpasswd name={{ website_user }} password={{ website_password }} owner=root group=apache mode=0640

- name: Deploy the website password protection
  template: src=password.conf dest=/etc/httpd/conf.d/{{ _website_domain }}.conf.d/password.conf
  notify: verify config and restart httpd
