- name: Remove the htpasswd file
  file:
    path: "/etc/httpd/{{ _website_domain }}.htpasswd"
    state: absent

- name: Remove the website password protection
  file:
    path: "/etc/httpd/conf.d/{{ _website_domain }}.conf.d/password.conf"
    state: absent
  notify: verify config and restart httpd
