- name: Remove the htpasswd file
  file:
    path: "{{ httpd_confdir }}/{{ _website_domain }}.htpasswd"
    state: absent

- name: Remove the website password protection
  file:
    path: "{{ _vhost_confdir }}/password.conf"
    state: absent
  notify: verify config and restart httpd
