---
- name: Set python.conf template for {{ _website_domain }}
  template:
    src: python.conf
    dest: "{{ _vhost_confdir }}/python.conf"
  notify: verify config and restart httpd

- name: Deploy WSGIDaemon for {{ _website_domain }}
  template:
    src: wsgi_daemon.conf
    dest: /etc/httpd/conf.d/wsgi_daemon_{{ _website_domain }}.conf
  notify: verify config and restart httpd
