- template: src=redirect_to_https.conf dest=/etc/httpd/conf.d/{{ _website_domain }}.conf.d/redirect_to_https.conf
  name: Set redirect_to_https.conf template for {{ _website_domain }}
  notify: verify config and restart httpd
