---

- name: Include distribution variables
  include: distro_vars.yml

- include: compat.yml

- name: Define vhost-specific variables
  set_fact:
    _use_tls: False
    _force_tls: False
    _vhost_conffile_prefix: "{{ httpd_vhost_confdir }}/{{ _website_domain }}"
    _vhost_confdir: "{{ httpd_vhost_confdir }}/{{ _website_domain }}.conf.d"

- name: Set use_tls
  set_fact:
    _use_tls: True
  when: use_letsencrypt or use_freeipa or use_tls

- name: Set force_tls if force_tls is defined
  set_fact:
    _force_tls: "{{ force_tls }}"
  when: force_tls

