---

- name: "Verify redirect value and fail"
  fail: msg="Redirect should be a complete URL, not {{ redirect }}"
  when: "redirect is defined and not redirect | match('^https?://.*/')"

- name: Include common vhost variables
  include_tasks: vhost_vars.yml

- name: Include common setup of httpd
  include_tasks: common.yml
  when: _httpd_common is not defined

- include_tasks: common_tls.yml
  when: _use_tls and _httpd_common_tls is not defined

- file:
    state: directory
    path: "{{ document_root }}"
    setype: httpd_sys_content_t
    owner: root
    group: "{{ document_root_group | default('root') }}"
    mode: 0775
  when: document_root is defined
  name: Set document root configuration

- file:
    path: "{{ _vhost_confdir }}"
    state: directory
  name: Create configuration directory for {{ _website_domain }}

# needed for newer apache, who requires at least 1 file for include
- copy:
    dest: "{{ _vhost_confdir }}/placeholder.conf"
    content: "# Placeholder"
  name: Create placeholder configuration for {{ _website_domain }}

- include_tasks: password.yml
  when: website_user is defined

- include_tasks: document_root.yml

- include_tasks: server_alias.yml

- include_tasks: mod_speling.yml

- name: Work on port 80 configuration
  set_fact:
    port: 80

- name: Generate vhost main HTTP conffile for {{ _website_domain }}
  template:
    src: vhost.conf
    dest: "{{ _vhost_conffile_prefix }}.conf"
    owner: root
    group: "{{ httpd_usergroup }}"
    mode: 0644
  notify: verify config and restart httpd

- include_tasks: redirect.yml

- include_tasks: redirects.yml

- include_tasks: aliases.yml

- include_tasks: letsencrypt.yml
  when: use_letsencrypt

- include_tasks: freeipa.yml
  when: use_freeipa

- include_tasks: mod_security.yml
  when: use_mod_sec

- include_tasks: redirect_to_https.yml

- include_tasks: wsgi.yml
  when: wsgi_script is defined and wsgi_script

- include_tasks: hidden_service.yml
  when: use_hidden_service

- name: Work on port 443 configuration
  set_fact:
    port: 443

- name: Generate vhost main HTTPS conffile for {{ _website_domain }}
  template:
    src: vhost.conf
    dest: "{{ _vhost_conffile_prefix }}_ssl.conf"
    owner: root
    group: "{{ httpd_usergroup }}"
    mode: 0644
  notify: verify config and restart httpd
  when: _use_tls

# cleanup of variables, since they leak to subsequent role run
#
# due to https://github.com/ansible/ansible/issues/14472
- set_fact:
    _force_tls: False
    _use_tls: False
  name: Clean force_tls and use_tls
