---

- name: Include common vhost variables
  include: vhost_vars.yml

- include: common_wsgi.yml
  when: _httpd_common_wsgi is not defined

- name: Set wsgi_daemon.conf template for WSGI instance {{ wsgi_instance }}
  template:
    src: wsgi_daemon.conf
    dest: "{{ httpd_global_confdir }}/wsgi_daemon_{{ wsgi_instance }}.conf"
  notify: verify config and restart httpd

- name: Set wsgi.conf template for WSGI instance {{ wsgi_instance }}
  template:
    src: wsgi.conf
    dest: "{{ _vhost_confdir }}/wsgi_{{ wsgi_instance }}.conf"
  notify: verify config and restart httpd

# TODO remove after May 2018
- name: Remove obsolete WSGI files
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - "{{ _vhost_confdir }}/python.conf"
    - "{{ _vhost_confdir }}/wsgi.conf"
  notify: verify config and restart httpd

